### ISSUE TITLE
Unify date and time in models

### ISSUE THREAD

**Issue by japhethwong** [theneutronchef/rails-proj2#1]
It seems like we may be better off just keeping track of a time (which includes a date) rather than two fields.  Thoughts?  (Applies to Car (depart_date, depart_time) and Trip (date, time))

**Comment by theneutronchef** [comment]
Car (depart_date + depart_time -> depart_datetime)
Trip (date + time -> datetime)

Merged the dates and times into a new column called datetime. We just have to parse the data out from datetime if we want to use them individually 
e.g. datetime.strftime.(FORMAT)
